from zamp_sdk.user_input.constants.actions import REQUEST_USER_INPUT_ACTION
from zamp_sdk.user_input.constants.hitl import (
    AWAITING_USER_INPUT,
    AWAITING_USER_INPUT_KEY,
    POST_ACTION_REQUIRED_FIELDS,
    POST_ACTION_RESUME_SCRIPT,
    POST_ACTION_RUN_CODE_EXECUTOR_WORKFLOW,
    SDK_USER_INPUT_EXIT_CODE,
    SDK_USER_INPUT_MARKER,
    USER_INPUT_WORKFLOW_PARAMS_KEY,
)

__all__ = [
    "AWAITING_USER_INPUT",
    "AWAITING_USER_INPUT_KEY",
    "POST_ACTION_REQUIRED_FIELDS",
    "POST_ACTION_RESUME_SCRIPT",
    "POST_ACTION_RUN_CODE_EXECUTOR_WORKFLOW",
    "USER_INPUT_WORKFLOW_PARAMS_KEY",
    "REQUEST_USER_INPUT_ACTION",
    "SDK_USER_INPUT_EXIT_CODE",
    "SDK_USER_INPUT_MARKER",
]
